force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <description>Assignment object for LWC and Apex class questions and has 4 custom fields.</description>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Long Text Area (3200) to store the description of the Assignments.</description>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <description>Due Date (Date) field to store the date of the Assignments.</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status (Picklist) for selecting the status of the Assignments.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Text Field to Store the Title of the Assignments</description>
    <label>Title</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AssignmentsList.cls
public with sharing class AssignmentsList {
    @AuraEnabled(cacheable=true)
    public static List<Assignment__c> getAssignmentList(){

        try{
            List<Assignment__c> result = [SELECT Title__c, Description__c, DueDate__c, Status__c FROM Assignment__c ORDER BY DueDate__c];

            return result;
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }


}